- name: Setup Gitea
  hosts: k3s
  tasks:
    - kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      with_items:
        - name: gitea
          url: https://dl.gitea.com/charts/
    - kubernetes.core.helm:
        name: gitea
        chart_ref: gitea/gitea
        release_namespace: gitea
        create_namespace: true
        kubeconfig: "{{ kubeconfig }}"
        values:
          gitea:
            admin:
              password: "{{ gitea_admin_password }}"
            additionalConfigFromEnvs:
              - name: GITEA__SERVER__SSH_DOMAIN
                value: "{{ ansible_default_ipv4.address }}"
              - name: GITEA__SERVER__SSH_PORT
                value: "30022"
              - name: GITEA__SERVER__ROOT_URL
                value: "http://{{ ansible_default_ipv4.address}}:30080"
          service:
            http:
              type: NodePort
              nodePort: 30080
            ssh:
              type: NodePort
              nodePort: 30022
